from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.video import Video
from app.schemas.compliance import ComplianceBreakdownResponse, ComplianceReportResponse
from app.services.compliance_service import compliance_service

router = APIRouter(prefix="/videos/{video_id}/compliance", tags=["compliance"])

DISCLAIMER = (
    "This compliance report is generated by automated analysis and should be reviewed "
    "by a qualified accessibility specialist. Scores are estimates based on AI analysis "
    "and may not reflect all accessibility considerations required by ADA/WCAG 2.1 AA."
)


@router.get("", response_model=ComplianceBreakdownResponse)
def get_compliance(video_id: str, db: Session = Depends(get_db)):
    video = db.query(Video).filter(Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")
    breakdown = compliance_service.compute_score(video_id, db)
    return breakdown


@router.get("/report", response_model=ComplianceReportResponse)
def get_compliance_report(video_id: str, db: Session = Depends(get_db)):
    video = db.query(Video).filter(Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")
    breakdown = compliance_service.compute_score(video_id, db)
    return ComplianceReportResponse(
        video_id=video.id,
        title=video.title,
        overall_score=breakdown.overall_score,
        caption_completeness=breakdown.caption_completeness,
        visual_coverage=breakdown.visual_coverage,
        manual_review=breakdown.manual_review,
        model_uncertainty=breakdown.model_uncertainty,
        ocr_reliability=breakdown.ocr_reliability,
        total_segments=breakdown.total_segments,
        high_risk_count=breakdown.high_risk_count,
        medium_risk_count=breakdown.medium_risk_count,
        low_risk_count=breakdown.low_risk_count,
        flags_count=breakdown.high_risk_count + breakdown.medium_risk_count,
        disclaimer=DISCLAIMER,
    )
