from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse, JSONResponse
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.video import Video
from app.models.segment import Segment
from app.services.caption_service import caption_service
from app.services.compliance_service import compliance_service
from app.services.youtube_service import youtube_service

router = APIRouter(prefix="/videos/{video_id}/export", tags=["export"])

DISCLAIMER = (
    "This compliance report is generated by automated analysis and should be reviewed "
    "by a qualified accessibility specialist. Scores are estimates based on AI analysis "
    "and may not reflect all accessibility considerations required by ADA/WCAG 2.1 AA."
)


@router.get("/vtt")
def export_vtt(video_id: str, db: Session = Depends(get_db)):
    video = db.query(Video).filter(Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")

    vtt = caption_service.get_latest_vtt(video_id, db)
    if not vtt:
        raise HTTPException(status_code=404, detail="No captions available")

    return PlainTextResponse(
        vtt,
        media_type="text/vtt",
        headers={
            "Content-Disposition": f'attachment; filename="{video.youtube_id}_captions.vtt"'
        },
    )


@router.get("/report")
def export_report(video_id: str, db: Session = Depends(get_db)):
    video = db.query(Video).filter(Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")

    breakdown = compliance_service.compute_score(video_id, db)

    segments = (
        db.query(Segment)
        .filter(Segment.video_id == video_id)
        .order_by(Segment.start_time)
        .all()
    )

    flags = []
    for seg in segments:
        if seg.risk_level in ("high", "medium"):
            flags.append({
                "start_time": seg.start_time,
                "end_time": seg.end_time,
                "risk_level": seg.risk_level,
                "risk_reason": seg.risk_reason,
                "transcript_text": seg.transcript_text,
                "ocr_text": seg.ocr_text,
                "ai_suggestion": seg.ai_suggestion,
                "review_status": seg.review_status,
            })

    report = {
        "video_id": video.id,
        "youtube_id": video.youtube_id,
        "title": video.title,
        "overall_score": breakdown.overall_score,
        "caption_completeness": breakdown.caption_completeness,
        "visual_coverage": breakdown.visual_coverage,
        "manual_review": breakdown.manual_review,
        "model_uncertainty": breakdown.model_uncertainty,
        "ocr_reliability": breakdown.ocr_reliability,
        "total_segments": breakdown.total_segments,
        "high_risk_count": breakdown.high_risk_count,
        "medium_risk_count": breakdown.medium_risk_count,
        "low_risk_count": breakdown.low_risk_count,
        "flags_count": len(flags),
        "flags": flags,
        "disclaimer": DISCLAIMER,
    }

    return JSONResponse(
        report,
        headers={
            "Content-Disposition": f'attachment; filename="{video.youtube_id}_report.json"'
        },
    )


@router.get("/validate")
def pre_upload_validation(video_id: str, db: Session = Depends(get_db)):
    """Check if a video is ready for upload. Blocks if critical issues remain."""
    video = db.query(Video).filter(Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")

    issues: list[dict] = []
    blocking = False

    # Must have captions
    vtt = caption_service.get_latest_vtt(video_id, db)
    if not vtt:
        issues.append({"severity": "critical", "message": "No captions available"})
        blocking = True

    # Check for unreviewed high-risk segments
    segments = (
        db.query(Segment)
        .filter(Segment.video_id == video_id)
        .all()
    )
    high_risk_pending = [
        s for s in segments
        if s.risk_level == "high" and s.review_status == "pending"
    ]
    if high_risk_pending:
        issues.append({
            "severity": "critical",
            "message": f"{len(high_risk_pending)} high-risk segment(s) not reviewed",
        })
        blocking = True

    med_risk_pending = [
        s for s in segments
        if s.risk_level == "medium" and s.review_status == "pending"
    ]
    if med_risk_pending:
        issues.append({
            "severity": "warning",
            "message": f"{len(med_risk_pending)} medium-risk segment(s) not reviewed",
        })

    # Check compliance score
    if video.compliance_score is not None and video.compliance_score < 50:
        issues.append({
            "severity": "warning",
            "message": f"Compliance score is low ({video.compliance_score:.1f}%)",
        })

    return {
        "ready": not blocking,
        "issues": issues,
        "total_segments": len(segments),
        "reviewed_count": sum(1 for s in segments if s.review_status in ("approved", "edited", "rejected")),
    }


@router.post("/upload")
def upload_to_youtube(video_id: str, db: Session = Depends(get_db)):
    video = db.query(Video).filter(Video.id == video_id).first()
    if not video:
        raise HTTPException(status_code=404, detail="Video not found")

    vtt = caption_service.get_latest_vtt(video_id, db)
    if not vtt:
        raise HTTPException(status_code=400, detail="No captions to upload")

    try:
        result = youtube_service.upload_captions(video.youtube_id, vtt, language="en")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"YouTube caption upload failed: {exc}") from exc

    video.status = "published"
    db.commit()
    return {
        "status": "success",
        "message": f"Captions uploaded to YouTube for video {video.youtube_id}",
        "youtube_id": video.youtube_id,
        "caption_track_id": result.get("id"),
    }
