import json
import logging
import subprocess
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaInMemoryUpload
from google_auth_oauthlib.flow import InstalledAppFlow

from app.config import settings
from app.mocks.mock_youtube import get_mock_metadata, get_mock_captions, extract_video_id, parse_iso8601_duration

YOUTUBE_UPLOAD_SCOPE = "https://www.googleapis.com/auth/youtube.force-ssl"
logger = logging.getLogger(__name__)


class YouTubeService:
    def get_video_metadata(self, url_or_id: str) -> dict:
        video_id = extract_video_id(url_or_id)
        if settings.USE_MOCKS:
            return get_mock_metadata(video_id)
        if not settings.YOUTUBE_API_KEY:
            raise RuntimeError("YOUTUBE_API_KEY is required when USE_MOCKS=false")

        youtube = build("youtube", "v3", developerKey=settings.YOUTUBE_API_KEY)
        try:
            response = youtube.videos().list(part="snippet,contentDetails", id=video_id).execute()
        except HttpError as exc:
            raise self._map_youtube_http_error(exc, video_id) from exc

        items = response.get("items", [])
        if not items:
            raise ValueError(
                f"Video not found or inaccessible: {video_id}. "
                "It may be private, removed, age-restricted, or blocked in your region."
            )

        snippet = items[0]["snippet"]
        duration_seconds = parse_iso8601_duration(items[0]["contentDetails"]["duration"])
        thumbnail_url = (
            snippet.get("thumbnails", {}).get("high", {}).get("url")
            or snippet.get("thumbnails", {}).get("default", {}).get("url")
            or ""
        )
        return {
            "youtube_id": video_id,
            "title": snippet.get("title", f"YouTube Video {video_id}"),
            "channel_title": snippet.get("channelTitle", ""),
            "description": snippet.get("description", ""),
            "published_at": snippet.get("publishedAt"),
            "thumbnail_url": thumbnail_url,
            "duration_seconds": duration_seconds,
        }

    def get_captions(self, video_id: str) -> str:
        if settings.USE_MOCKS:
            return get_mock_captions(video_id)
        out_dir = Path(settings.VIDEO_CACHE_DIR)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_template = str(out_dir / "%(id)s")
        url = f"https://www.youtube.com/watch?v={video_id}"

        # Try autogenerated subtitles first, then manual subtitles.
        try:
            self._run_yt_dlp(
                [
                    "--skip-download",
                    "--write-auto-sub",
                    "--sub-langs",
                    "en.*,en",
                    "--sub-format",
                    "vtt",
                    "-o",
                    out_template,
                    url,
                ]
            )
        except RuntimeError:
            # Auto captions are not always available; fallback to manual subtitles below.
            pass
        caption_file = self._find_caption_file(out_dir, video_id)
        if not caption_file:
            self._run_yt_dlp(
                [
                    "--skip-download",
                    "--write-sub",
                    "--sub-langs",
                    "en.*,en",
                    "--sub-format",
                    "vtt",
                    "-o",
                    out_template,
                    url,
                ]
            )
            caption_file = self._find_caption_file(out_dir, video_id)

        if not caption_file:
            raise RuntimeError(f"No English captions found for video {video_id}")
        return caption_file.read_text(encoding="utf-8")

    def upload_captions(self, video_id: str, vtt: str, language: str = "en") -> dict:
        if settings.USE_MOCKS:
            return {"id": "mock-caption-id", "status": "mock"}

        youtube = build("youtube", "v3", credentials=self._get_oauth_credentials())
        media = MediaInMemoryUpload(vtt.encode("utf-8"), mimetype="text/vtt", resumable=False)

        existing = youtube.captions().list(part="snippet", videoId=video_id).execute()
        items = existing.get("items", [])
        match = next((item for item in items if item.get("snippet", {}).get("language") == language), None)

        body = {
            "snippet": {
                "videoId": video_id,
                "language": language,
                "name": "AVCE Captions",
                "isDraft": False,
            }
        }

        if match:
            body["id"] = match["id"]
            return youtube.captions().update(part="snippet", body=body, media_body=media).execute()
        return youtube.captions().insert(part="snippet", body=body, media_body=media).execute()

    def _map_youtube_http_error(self, exc: HttpError, video_id: str) -> Exception:
        status = getattr(exc.resp, "status", None)
        reason, message = self._extract_http_error_details(exc)
        logger.warning(
            "YouTube Data API videos.list failed video_id=%s status=%s reason=%s message=%s",
            video_id,
            status,
            reason,
            message,
        )

        auth_reasons = {
            "keyInvalid",
            "API_KEY_INVALID",
            "API_KEY_SERVICE_BLOCKED",
            "accessNotConfigured",
            "forbidden",
            "ipRefererBlocked",
        }
        quota_reasons = {"quotaExceeded", "dailyLimitExceeded", "rateLimitExceeded", "userRateLimitExceeded"}

        if reason in quota_reasons:
            return RuntimeError("YouTube API quota exceeded. Try again later.")
        if reason in auth_reasons:
            return RuntimeError(
                f"YouTube API credentials/config error ({reason}). "
                "Verify YOUTUBE_API_KEY and Google Cloud API restrictions."
            )
        if status == 404 or reason == "videoNotFound":
            return ValueError(f"Video not found: {video_id}")
        if status == 403:
            return ValueError(
                f"Video is inaccessible: {video_id}. It may be private, removed, or region-restricted."
            )

        detail = message or str(exc)
        return RuntimeError(f"YouTube API request failed (status={status}, reason={reason or 'unknown'}): {detail}")

    def _extract_http_error_details(self, exc: HttpError) -> tuple[str | None, str | None]:
        content = exc.content
        if isinstance(content, bytes):
            payload = content.decode("utf-8", errors="ignore")
        else:
            payload = str(content)
        try:
            data = json.loads(payload)
        except json.JSONDecodeError:
            return None, payload.strip() or None

        error = data.get("error", {})
        message = error.get("message")
        errors = error.get("errors") or []
        reason = None
        if errors and isinstance(errors, list):
            first = errors[0] or {}
            reason = first.get("reason")
            message = first.get("message") or message
        return reason, message

    def _find_caption_file(self, out_dir: Path, video_id: str) -> Path | None:
        candidates = sorted(out_dir.glob(f"{video_id}*.vtt"))
        return candidates[0] if candidates else None

    def _run_yt_dlp(self, args: list[str]) -> None:
        command = [settings.YT_DLP_BINARY, *args]
        try:
            subprocess.run(command, check=True, capture_output=True, text=True)
        except FileNotFoundError as exc:
            raise RuntimeError(f"yt-dlp not found at '{settings.YT_DLP_BINARY}'") from exc
        except subprocess.CalledProcessError as exc:
            stderr = (exc.stderr or "").strip()
            stdout = (exc.stdout or "").strip()
            details = stderr or stdout or "Unknown yt-dlp error"
            raise RuntimeError(f"Failed to download YouTube captions: {details}") from exc

    def _get_oauth_credentials(self) -> Credentials:
        token_path_str = settings.YOUTUBE_OAUTH_TOKEN_FILE
        client_secrets = settings.YOUTUBE_OAUTH_CLIENT_SECRETS_FILE
        if not token_path_str:
            raise RuntimeError("YOUTUBE_OAUTH_TOKEN_FILE must be set for caption upload")
        if not client_secrets:
            raise RuntimeError("YOUTUBE_OAUTH_CLIENT_SECRETS_FILE must be set for caption upload")

        token_path = Path(token_path_str)
        creds = None
        if token_path.exists():
            creds = Credentials.from_authorized_user_file(str(token_path), [YOUTUBE_UPLOAD_SCOPE])

        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())

        if not creds or not creds.valid:
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets, [YOUTUBE_UPLOAD_SCOPE])
            creds = flow.run_local_server(port=0)
            token_path.parent.mkdir(parents=True, exist_ok=True)
            token_path.write_text(creds.to_json(), encoding="utf-8")

        if not creds:
            raise RuntimeError("Failed to obtain YouTube OAuth credentials")
        return creds


youtube_service = YouTubeService()
